import pandas as pd
import re
import numpy as np


def extract_skills(sample="All"):
    print('\n Extracting skills from Job Description')
    df = pd.read_parquet("Final_Data/" + sample + "/merged.parquet")

    skillss = [
        " Android/iOS development ",
        " CI/CD (Continuous Integration/Continuous Deployment) ",
        " CI/CD ",
        " Data structures ",
        " Algorithms ",
        " Testing ",
        " Prototyping ",
        " Development ",
        " Agile ",
        " Concurrency ",
        " Parallelism ",
        " Multi-threading ",
        " Scraping ",
        " Distributed system ",
        " Quality Analyst ",
        " TDD ",
        " Test Driven Development ",
        " Backend (Computer Programming) ",
        " Backend ",
        " Frontend ",
        " Software Architecture ",
        " OOD (Object-Oriented Design) ",
        " Functional Programming ",
        " Computer Network ",
        " Cloud Computing ",
        " Object-Oriented Programming ",
        " Scripting ",
        " SDLC (Software Development Life Cycle) ",
        " SDLC ",
        " REST ",
        " gRPC ",
        " GraphQL ",
        " Protocol Buffer ",
        " Full-stack web application development ",
        " Virtualization ",
        " Containerization ",
        " Web technologies ",
        " Web Development ",
        " Mechanical System ",
        " Structural Analysis ",
        " Finite Element Analysis ",
        " FEM Mesh Analysis ",
        " Engineering Design ",
        " Fluid Mechanics ",
        " Manufacturing Processes ",
        " FMEA 8D ",
        " HVAC ",
        " CAD Design ",
        " 3D Printing ",
        " Structural Analysis (Tools) ",
        " Project Management ",
        " Steel Structures ",
        " Stress Analysis ",
        " Solid Mechanics ",
        " Fixture Design ",
        " Building Information Model ",
        " Meshing ",
        " Six Sigma 5S ",
        " Design Optimization ",
        " Material Modeling ",
        " Kaizen ",
        " Construction Management ",
        " Applied Solid Mechanics ",
        " Failure Analysis ",
        " Surveying and Mapping ",
        " Numerical Methods ",
        " Manufacturing Process Controls ",
        " Prototype Design ",
        " Geospatial Information Systems (GIS) ",
        " FEA  ",
        " Building Information Modeling ",
        " Process Design ",
        " Cost Estimating ",
        " Contract Administration ",
        " CNC Machining ",
        " Additive Manufacturing ",
        " Mechanical Analysis ",
        " Data Visualization ",
        " Data Warehousing ",
        " Requirements Gathering ",
        " Critical Thinking ",
        " Collaboration ",
        " Data Cleaning ",
        " Data Architecture ",
        " Project Management ",
        " Leadership ",
        " Teamwork ",
        " Coding ",
        " Enterprise Resource Planning (ERP) ",
        " Analytical Skills ",
        " Communication ",
        " Operating System ",
        " Modeling/Diagramming ",
        " Problem Solving ",
        " Time Management ",
        " Linear Algebra and Calculus ",
        " Machine Learning ",
        " Wireframing ",
        " Customer Relationship Management (CRM) ",
        " Technical Expertise ",
        " Adaptability ",
        " Inbound Marketing ",
        " Design Thinking ",
        " Conflict Resolution ",
        " Agile Project Planning ",
        " Extract Transform Load (ETL) ",
        " Scrum ",
        " Project Scoping ",
        " Documentation ",
        " Change Management ",
        " Roadmapping ",
        " Extract Load Transform (ELT) ",
        " Gantt Charts ",
        " Kanban boards ",
        " Statistical Analysis ",
        " Data Mining ",
        " Data Modeling ",
        " Analytics ",
        " Software Development ",
        " Data Pipeline Development ",
        " Cloud Computing ",
        " Process Modeling ",
        " Requirements Elicitation ",
        " Business Acumen ",
        " Product Strategy ",
        " User Research ",
        " Agile Methodology ",
        " Budgeting ",
        " Resource Management ",
        " Risk Management "
    ]

    languages = [
        " Java ",
        " .NET ",
        " Python ",
        " C++ ",
        " JavaScript ",
        " TypeScript ",
        " React ",
        " Vue ",
        " Angular ",
        " Svelte ",
        " C# ",
        " Golang ",
        " Go ",
        " Kotlin ",
        " PHP ",
        " Swift ",
        " Erlang ",
        " Elixir ",
        " Scala ",
        " HTML ",
        " CSS ",
        " TypeScript ",
        " VBA ",
        " R ",
        " Objective-C ",
        " Bash ",
        " Shell ",
        " Powershell ",
        " VBA ",
        " Matlab ",
        " Octave ",
        " T-SQL ",
        " SQL ",
        " NoSQL ",
    ]

    databases = [
        " MongoDB ",
        " PostgreSQL ",
        " MySQL ",
        " MS SQL ",
        " MS-SQL ",
        " Oracle DB ",
        " Cassandra ",
        " Neo4J ",
    ]

    cloud = [
        " Amazon Web Services (AWS) ",
        " AWS ",
        " Microsoft Azure ",
        " Google Cloud Platform (GCP) ",
        " GCP ",
        " BigQuery ",
        " Snowflake ",
        " Databricks ",
        " Redshift ",
        " Openshift ",
        " Firebase ",
    ]

    tools = [
        " Docker ",
        " Kubernetes ",
        " Jenkins ",
        " Jira ",
        " Github Actions ",
        " Circle CI ",
        " Bitbucket ",
        " Sentry ",
        " AutoCAD ",
        " ANSYS ",
        " Creo Simulate (Mechanica) ",
        " SOLIDWORKS ",
        " Revit ",
        " Abaqus ",
        " Fusion 360 ",
        " SketchUp ",
        " Nastran ",
        " OpenFOAM ",
        " HyperWorks ",
        " Autodesk Inventor ",
        " MS Project ",
        " SolidWorks Simulation ",
        " Femap ",
        " Microsoft Office ",
        " Civil 3D ",
        " CATIA ",
        " SimScale ",
        " MicroStation ",
        " COMSOL ",
        " Plaxis ",
        " HyperMesh ",
        " AUTOPIPE ",
        " ArcGIS ",
        " OptiStruct ",
        " PVElite ",
        " CAM Software ",
        " GeoStudio ",
        " MSC Adams ",
        " SAP2000 ",
        " LS-DYNA ",
        " STAAD.Pro ",
        " PTC Creo ",
        " HEC-RAS ",
        " Minitab ",
        " Taitherm ",
        " Trimble ",
        " Bluebeam Revu ",
        " Microsoft Power BI ",
        " Apache Spark ",
        " Microsoft Office ",
        " Pendo ",
        " SAP Business Objects ",
        " Apache Hadoop ",
        " Microsoft Suite ",
        " Amplitude ",
        " Sisense ",
        " Apache Kafka ",
        " Wrike ",
        " Aha ",
        " TIBCO Software ",
        " Tableau ",
        " Oracle NetSuite ",
        " Jira ",
        " Thoughtspot ",
        " Snowflake ",
        " Pencil ",
        " Confluence ",
        " Qlik ",
        " Apache Hive ",
        " Trello ",
        " SAS Business Intelligence ",
        " Amazon Redshift ",
        " Xplenty ",
        " Gainsight ",
        " HubSpot ",
        " Google Analytics ",
        " Google Data Studio ",
        " Apache Cassandra ",
        " Salesforce ",
        " Looker Redash ",
        " Looker ",
        " Zoho ",
        " Periscope Data ",
        " Amazon Athena ",
        " Balsamiq ",
        " Metabase ",
        " Power BI ",
        " Figma ",
        " Jupyter Notebook ",
        " SAS ",
        " Plotly ",
        " Azure DevOps ",
        " IBM Cognos ",
        " Apache Airflow ",
        " ServiceNow ",
        " Chartio ",
        " Big Query ",
        " Infogram ",
        " Excel ",
        " KNIME ",
        " dbt ",
        " Swagger ",
        " RapidMiner ",
        " Fivetran ",
        " Powerpoint ",
        " Monday.com ",
        " Domo ",
        " Stitch ",
        " Word ",
        " Oracle Analytics Cloud ",
        " PostgreSQL ",
        " SAP ",
        " Azure DevOps ",
        " Prefect ",
        " Alteryx ",
        " Secoda ",
        " DAX ",
        " Apache Storm ",
        " Apache Flume ",
        " Outlook ",
        " Apache Sqoop ",
        " QlikWavefront ",
        " SSIS Azure DevOps ",
        " SSRS ",
        " Visio ",
        " Google Sheets ",
        " SPSS ",
        " Sharepoint ",
        " Git ",
        " Docker ",
        " Kafka ",
        " Jira ",
        " Aha ",
        " Asana ",
        " MS Project ",
        " SAS "
    ]

    Skills = {
        'Language': list(set(languages)),
        "Cloud": list(set(cloud)),
        "Database": list(set(databases)),
        "Skill": list(set(skillss)),
        "Tool": list(set(tools))
    }

    skills_list = []
    for i, rows in df.iterrows():
        id = rows["Key"]
        category = rows["Category"]
        desc = rows["Description"]
        exp = rows["Experience_Level"]
        for skl_code, skls in Skills.items():
            for sk in skls:
                if desc is not None:
                    if re.search(re.escape(sk), desc, re.IGNORECASE) is not None:
                        skills_list.append([sk, id, category, exp, skl_code])

    with open('Final_Data/' + sample + '/all_skills.tsv', 'w') as file:
        for i in skills_list:
            b = "\t".join(i) + "\n"
            file.write(b)
    file.close()
